### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Typodin** [Temus/JotX#2]
При выводе последних комментариев отдельно через 

[!JotX? &action=`lastcomments` !]

Они нормально отображаются, но попытка модерировать или или редактировать приводит к ошибке работы сайта (белый экарн). Плюс ссылка на последний комментарий при таком выводе бесполезна если сам комментарий находится на другой странице.

**Comment by dmitriy71n** [comment]
Evolution CMS 1.4.31, php8.1

Fatal error: Uncaught Error: Attempt to assign property "path" on null in /site.name/assets/snippets/jot/jot.class.inc.php:46 Stack trace: #0 /site.name/assets/snippets/jot/snippet.jot.php(105): CJot->Run() #1 /site.name/manager/includes/document.parser.class.inc.php(2024) : eval()'d code(1): require('/sites/site.dev...') #2 /site.name/manager/includes/document.parser.class.inc.php(2024): eval() #3 /site.name/manager/includes/document.parser.class.inc.php(2175): DocumentParser->evalSnippet('return require ...', Array) #4 /site.name/manager/includes/document.parser.class.inc.php(2087): DocumentParser->_get_snip_result('JotX? &config=`...') #5 /site.name/manager/includes/document.parser.class.inc.php(2785): DocumentParser->evalSnippets('\r\n<!doctype htm...') #6 /site.name/manager/includes/document.parser.class.inc.php(976): DocumentParser->parseDocumentSource('[[countViews? &...') #7 /site.name/manager/includes/document.parser.class.inc.php(3057): DocumentParser->outputContent() #8 /site.name/manager/includes/document.parser.class.inc.php(2933): DocumentParser->prepareResponse() #9 /site.name/index.php(145): DocumentParser->executeParser() #10 {main} thrown in /site.name/assets/snippets/jot/jot.class.inc.php on line 46
